/**
 * skills-loader.ts
 *
 * Dual-environment loader for skill and agent content.
 *
 * - **Vercel / Edge**: reads from the build-time JSON cache imported at compile time.
 * - **Local dev (Node.js)**: falls back to `fs.readFile` so edits to skill/agent
 *   files are reflected immediately without rebuilding the cache.
 *
 * The cache is generated by `scripts/build-skills-cache.ts` (runs as `prebuild`).
 */

import cache from "./skills-cache.json";

// ── Types ──────────────────────────────────────────────────────────────────────

export interface SkillsCache {
  skills: Record<string, string>;
  agents: Record<string, string>;
}

// ── Environment Detection ──────────────────────────────────────────────────────

/**
 * Returns `true` when running in a Node.js environment where the `fs` module
 * is available (i.e. local development). Returns `false` on Edge / Vercel.
 */
function isNodeJs(): boolean {
  return (
    typeof process !== "undefined" &&
    typeof process.versions !== "undefined" &&
    typeof process.versions.node !== "undefined"
  );
}

// ── Lazy fs import (only in Node.js) ──────────────────────────────────────────

let fsModule: typeof import("fs") | null = null;
let pathModule: typeof import("path") | null = null;

async function getFs() {
  if (fsModule) return fsModule;
  if (!isNodeJs()) return null;
  fsModule = await import("fs");
  return fsModule;
}

async function getPath() {
  if (pathModule) return pathModule;
  if (!isNodeJs()) return null;
  pathModule = await import("path");
  return pathModule;
}

// ── Filesystem Fallback Paths ──────────────────────────────────────────────────

const PROJECT_ROOT =
  typeof __dirname !== "undefined"
    ? (() => {
        // src/lib → project root (2 levels up)
        const path = require("path");
        return path.resolve(__dirname, "..", "..");
      })()
    : "";

const SKILLS_DIR = PROJECT_ROOT ? `${PROJECT_ROOT}/skills` : "";
const AGENTS_DIR = PROJECT_ROOT ? `${PROJECT_ROOT}/agents` : "";

// ── Public API ─────────────────────────────────────────────────────────────────

/**
 * Get the full markdown content for a skill by its ID.
 *
 * 1. Looks up the build-time JSON cache first (works everywhere).
 * 2. If not found AND running in Node.js, falls back to reading the file
 *    directly from the filesystem (useful during local development).
 *
 * @param skillId - The kebab-case skill directory name (e.g. "flutter-dart-code-review")
 * @returns The skill markdown content, or `null` if not found.
 */
export async function getSkillContent(skillId: string): Promise<string | null> {
  // 1. Try the bundled cache
  const cached = (cache as SkillsCache).skills[skillId];
  if (cached !== undefined) {
    return cached;
  }

  // 2. Filesystem fallback (Node.js only)
  if (isNodeJs() && SKILLS_DIR) {
    const fs = await getFs();
    const path = await getPath();
    if (fs && path) {
      const filePath = path.join(SKILLS_DIR, skillId, "SKILL.md");
      try {
        const content = await fs.promises.readFile(filePath, "utf-8");
        return content;
      } catch {
        // File doesn't exist or isn't readable
        return null;
      }
    }
  }

  return null;
}

/**
 * Get the full markdown content for an agent by its ID.
 *
 * 1. Looks up the build-time JSON cache first (works everywhere).
 * 2. If not found AND running in Node.js, falls back to reading the file
 *    directly from the filesystem (useful during local development).
 *
 * @param agentId - The agent filename without .md (e.g. "code-reviewer")
 * @returns The agent markdown content, or `null` if not found.
 */
export async function getAgentContent(agentId: string): Promise<string | null> {
  // 1. Try the bundled cache
  const cached = (cache as SkillsCache).agents[agentId];
  if (cached !== undefined) {
    return cached;
  }

  // 2. Filesystem fallback (Node.js only)
  if (isNodeJs() && AGENTS_DIR) {
    const fs = await getFs();
    const path = await getPath();
    if (fs && path) {
      const filePath = path.join(AGENTS_DIR, `${agentId}.md`);
      try {
        const content = await fs.promises.readFile(filePath, "utf-8");
        return content;
      } catch {
        // File doesn't exist or isn't readable
        return null;
      }
    }
  }

  return null;
}

/**
 * List all skill IDs available in the cache.
 */
export function listSkillIds(): string[] {
  return Object.keys((cache as SkillsCache).skills);
}

/**
 * List all agent IDs available in the cache.
 */
export function listAgentIds(): string[] {
  return Object.keys((cache as SkillsCache).agents);
}
